export type Resource = {
  id: string;
  title: string;
  description: string;
  category: string;
  categoryColor: 'blue' | 'cyan' | 'purple' | 'green' | 'orange';
  type: 'Course' | 'Book' | 'Docs' | 'Tool' | 'Cheatsheet' | 'Video';
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  url: string;
  icon: string;
  tags: string[];
};

export const resources: Resource[] = [
  {
    id: '1',
    title: 'AWS Documentation',
    description: 'The official AWS docs — always the ground truth for services like EC2, EKS, RDS, WAF, and over 200+ services. Bookmark the Architecture Center too.',
    category: 'AWS',
    categoryColor: 'orange',
    type: 'Docs',
    level: 'Intermediate',
    url: 'https://docs.aws.amazon.com/',
    icon: '☁️',
    tags: ['AWS', 'Cloud', 'Reference'],
  },
  {
    id: '2',
    title: 'Kubernetes Official Documentation',
    description: 'Complete Kubernetes docs covering concepts, API reference, tasks, and tutorials. The Concepts section is essential reading for anyone running k8s in production.',
    category: 'Kubernetes',
    categoryColor: 'cyan',
    type: 'Docs',
    level: 'Intermediate',
    url: 'https://kubernetes.io/docs/',
    icon: '⎈',
    tags: ['Kubernetes', 'Containers', 'Orchestration'],
  },
  {
    id: '3',
    title: 'The Phoenix Project',
    description: 'A novel about DevOps transformation — follows an IT manager fixing a failing project. Changes how you think about work, flow, and feedback loops. Must-read.',
    category: 'DevOps Culture',
    categoryColor: 'purple',
    type: 'Book',
    level: 'Beginner',
    url: 'https://itrevolution.com/the-phoenix-project/',
    icon: '📖',
    tags: ['Culture', 'DevOps', 'DORA'],
  },
  {
    id: '4',
    title: 'Terraform: Up & Running (3rd Ed.)',
    description: 'The definitive guide to Terraform by Yevgeniy Brikman. Covers modules, state management, testing, and running Terraform in teams. Highly practical.',
    category: 'IaC',
    categoryColor: 'purple',
    type: 'Book',
    level: 'Intermediate',
    url: 'https://www.oreilly.com/library/view/terraform-up-and/9781098116736/',
    icon: '📚',
    tags: ['Terraform', 'IaC', 'AWS'],
  },
  {
    id: '5',
    title: 'Linux Command Line Cheatsheet',
    description: 'A comprehensive reference for Linux commands — file operations, networking, process management, grep, awk, sed. Essential for any DevOps engineer daily.',
    category: 'Linux',
    categoryColor: 'green',
    type: 'Cheatsheet',
    level: 'Beginner',
    url: 'https://cheatsheet.dennyzhang.com/cheatsheet-linux-A4',
    icon: '🐧',
    tags: ['Linux', 'Bash', 'Shell'],
  },
  {
    id: '6',
    title: 'Docker Official Documentation',
    description: 'Complete Docker docs — from basics to advanced topics like multi-stage builds, Docker Compose, networking, volumes, and the Docker daemon internals.',
    category: 'Containers',
    categoryColor: 'blue',
    type: 'Docs',
    level: 'Beginner',
    url: 'https://docs.docker.com/',
    icon: '🐳',
    tags: ['Docker', 'Containers', 'Dockerfile'],
  },
  {
    id: '7',
    title: 'Prometheus & Grafana for Beginners — KodeKloud',
    description: 'Hands-on course covering Prometheus architecture, PromQL queries, recording rules, alerts, and building production-grade Grafana dashboards.',
    category: 'Observability',
    categoryColor: 'green',
    type: 'Course',
    level: 'Beginner',
    url: 'https://kodekloud.com/courses/monitoring-with-prometheus/',
    icon: '📊',
    tags: ['Prometheus', 'Grafana', 'Monitoring'],
  },
  {
    id: '8',
    title: 'GitHub Actions Documentation',
    description: 'Official docs for GitHub Actions — workflow syntax, reusable workflows, secrets management, self-hosted runners, and CI/CD best practices.',
    category: 'CI/CD',
    categoryColor: 'blue',
    type: 'Docs',
    level: 'Beginner',
    url: 'https://docs.github.com/en/actions',
    icon: '⚙️',
    tags: ['GitHub', 'CI/CD', 'Automation'],
  },
  {
    id: '9',
    title: 'CKA Exam Prep — Kubernetes The Hard Way',
    description: "Kelsey Hightower's famous guide to bootstrapping Kubernetes from scratch. Understanding this deeply prepares you for the CKA and makes k8s concepts click.",
    category: 'Kubernetes',
    categoryColor: 'cyan',
    type: 'Course',
    level: 'Advanced',
    url: 'https://github.com/kelseyhightower/kubernetes-the-hard-way',
    icon: '🎓',
    tags: ['Kubernetes', 'CKA', 'Certification'],
  },
  {
    id: '10',
    title: 'OWASP Top Ten',
    description: 'The most critical web application security risks — essential reading for anyone doing DevSecOps, setting up WAF rules, or code-reviewing applications.',
    category: 'Security',
    categoryColor: 'orange',
    type: 'Docs',
    level: 'Intermediate',
    url: 'https://owasp.org/www-project-top-ten/',
    icon: '🔒',
    tags: ['Security', 'OWASP', 'DevSecOps'],
  },
  {
    id: '11',
    title: 'Bash Scripting Cheatsheet',
    description: 'Quick reference for Bash scripting — variables, loops, conditionals, functions, arrays, string manipulation, and common patterns for automation scripts.',
    category: 'Scripting',
    categoryColor: 'green',
    type: 'Cheatsheet',
    level: 'Beginner',
    url: 'https://devhints.io/bash',
    icon: '💻',
    tags: ['Bash', 'Scripting', 'Automation'],
  },
  {
    id: '12',
    title: 'Google SRE Book (Free)',
    description: "Google's Site Reliability Engineering book — covers error budgets, SLOs/SLAs, production readiness reviews, postmortems, and on-call practices. Free online.",
    category: 'SRE',
    categoryColor: 'purple',
    type: 'Book',
    level: 'Advanced',
    url: 'https://sre.google/sre-book/table-of-contents/',
    icon: '🔧',
    tags: ['SRE', 'Reliability', 'Operations'],
  },
];
